### ISSUE TITLE
How to set match_parent width?

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [tangqi92/WaveLoadingView#12]

**Comment by tangqi92** [comment]
Hi,

WaveLoadingView extends View, so you can use it like a common view. I mean, you can set it like this

```
android:layout_width="100dp"
android:layout_height="100dp"
```

**Comment by FranciscoJavierPRamos** [comment]
Does not work, you still have a fixed size...

**Comment by tangqi92** [comment]
Can you give me see your code?

**Comment by FranciscoJavierPRamos** [comment]
<me.itangqi.waveloadingview.WaveLoadingView
        android:id="@+id/waveLoadingView"
        android:layout_width="match_parent"
        android:layout_gravity="center|top"
        android:foregroundGravity="top"
        app:wlv_shapeType="rectangle"
        android:layout_height="220dp"/>


The width of the view is everything but the wave is limited...

**Comment by tangqi92** [comment]
hi @FranciscoJavierPRamos 

It's my fault.

I've updated the latest code, has been updated to version 0.2.2.

You can view the update log.

**Comment by FranciscoJavierPRamos** [comment]
I want to put the maximum width but does not work

![captura de pantalla 2016-05-23 a las 9 50 38 a m](https://cloud.githubusercontent.com/assets/7097754/15474941/d9805224-20cc-11e6-9712-e771b25a8183.png)

**Comment by cabrinhaFx** [comment]
Have same issues,

tried to use the rectangle to fill my parent view with android:layout_width="match_parent". Nothing changes till app:wlv_rectangle_height="1000" and I get the same black box.

**Comment by tangqi92** [comment]
Hi @FranciscoJavierPRamos @cabrinhaFx 

I have updated the library to version 0.3.0.

I have removed the app:wlv_rectangle_width/height, you can directly change the width/height.

**Comment by FranciscoJavierPRamos** [comment]
Thanks!! I will try it...
