### ISSUE TITLE
How to change the frequency of the waves ?

### ISSUE THREAD

**Issue by caminin** [tangqi92/WaveLoadingView#13]
This widget is truly beautiful, but i need to lower the frequency of the waves, because there are many things shown on my screen and I need to have a focus somewhere else.

Is there a way to do it easily ? If not, where can I try to do it ?

Thanks for your work :-D

**Comment by tangqi92** [comment]
Hi,

Lower the frequency of the waves? You can try to use attributes 'wlv_waveAmplitude' in .xml or 'mWaveLoadingView.setAmplitudeRatio()' in .java

Hope this will achieve the effect you want.：D

**Comment by caminin** [comment]
I was thinking about one wave every ten seconds, i already tried to use waveAmplitude and it was nearly enough, but i want to try something else.

I'm wondering if it's possible to do this : 
1) one wave
2) three seconds with nothing
3) Another wave

**Comment by tangqi92** [comment]
Oh, I see what you mean, but this demand sounds a bit strange.

Now I'm trying to fix an urgent bug, if time permits, I will try to try to achieve the effect you want.

Thank you for your support.

**Comment by caminin** [comment]
Ok, don't spend too much time on it, your work is good as it is now. Good luck with your bug !

**Comment by radaced** [comment]
It's not exactly the same request, but it would also be cool to adjust the animation duration of the wave. As far as I saw in your code it is fixed to 1 sec (1000msec). If you could add a simple parameter to adjust this value as well that would be great.

Anyways thanks for the work and great job. :+1:

**Comment by tangqi92** [comment]
Hi @caminin @radaced 

I am very very sorry to reply to you so late.

I just updated the library to v0.3.5, now it supports to change the frequency of the waves .

You just need to call the method 'setAnimDuration()'.

I hope you will like it.
Finally, thank you for your support.

**Comment by caminin** [comment]
Thx a lot, It's gonna be really useful !
