### ISSUE TITLE
How to change the width and height of the waves?

### ISSUE THREAD

**Issue by addio3305** [tangqi92/WaveLoadingView#16]
Hi.

I need to change the width and height of the square waves but I can't.

For example, if I set the layout_width to 30dp and layout_height to 100dp, 

the square is drawn the square which has 30dp width and height, not 30dp width and 100dp height.

Is there any way to set the width and height? 

Thanks for your work. ^_^

**Comment by tangqi92** [comment]
Hi.

Are you sure you need a square rather than rectangular?

**Comment by addio3305** [comment]
Oh, this is my mistake. Sorry. 

I can use rectangular rather than square. 

Thank you. :-D
