### ISSUE TITLE
关于控件中的背景颜色的更改

### ISSUE THREAD

**Issue by GreatGarlic** [tangqi92/WaveLoadingView#18]
如何更改控件中的背景颜色？

**Comment by tangqi92** [comment]
你可以试一下 「wlv_waveColor」 属性与 「setWaveColor」 方法

**Comment by GreatGarlic** [comment]
@tangqi92 我的意思是空白区域的颜色，我尝试使用 android:background属性，发现周边矩形颜色一起改变了

**Comment by tangqi92** [comment]
@GreatGarlic 抱歉，目前还不能实现，如果你十分需要，可以试着修改下源码：）

**Comment by GreatGarlic** [comment]
@tangqi92 好的，谢谢了 : )

**Comment by GreatGarlic** [comment]
@tangqi92 亲,我把我想要实现的功能给你PR了 : )
