### ISSUE TITLE
borderWidth这个属性和系统的属性有冲突

### ISSUE THREAD

**Issue by sfsheng0322** [tangqi92/WaveLoadingView#2]
您的：app:borderWidth (integer) Default to be 0
编译出错：Error:(2) Attribute "borderWidth" has already been defined

**Comment by tangqi92** [comment]
@sfsheng0322 请问你是不是使用了 Android Design Support Library ，抱歉，由于发布前没有经过详细地测试，给你带来了困扰，稍后我会对所有属性添加前缀以避免冲突，感谢你的反馈：）

**Comment by sfsheng0322** [comment]
嗯嗯
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:design:23.1.1'

**Comment by tangqi92** [comment]
@sfsheng0322 你好，bug 已经修掉了，但是最新的 0.1.4 版本还没审核，所以现在你可以试着手动导入，再次感谢反馈！

**Comment by sfsheng0322** [comment]
谢谢啦，唐琪？

**Comment by ParhamAhmadi** [comment]
thanks @tangqi92  
but when i compile this an error will be occured like the statement below:
"java.lang.IllegalArgumentException: width and height must be > 0"
how should i fix this ?
I'm waiting for your answer.
Regards

**Comment by tangqi92** [comment]
@ParhamAhmadi 

Do you mind the xml posted here ?

Because according to your error message, I am currently unable to determine what went wrong.

**Comment by ParhamAhmadi** [comment]
@tangqi92 
It's working correctly without code :
  mWaveLoadingView.setWaveColor(Color.GRAY);

OR this :
   mWaveLoadingView.setBorderColor(Color.GRAY);
but when i add the code , the error will be occurred with the text of : 
"java.lang.IllegalArgumentException: width and height must be > 0"
and when i remove the code , it work good.
i don't know why this error occurs.
i really need it to work for my new android project by i can't compile it because of this error.

Thanks for your good supporting of this issue.

**Comment by tangqi92** [comment]
@ParhamAhmadi Hi
Sorry to keep you waiting, I made a stupid mistake, and now has been fixed. You can try to use the latest version 0.1.5 which i just updated.

Thank you for your support again!

**Comment by ParhamAhmadi** [comment]
Thanks,I will test it again now
Regards

**Comment by androidjx** [comment]
您好：我使用了 Android Design Support Library ，但是报“Error:(186) Attribute "borderWidth" has already been defined”错 。compile 'com.android.support:design:23.3.0'我用的是3.0的

**Comment by tangqi92** [comment]
@androidjx 

你好，你能贴下具体的代码吗？

**Comment by androidjx** [comment]
D:\aspath\3CTV\starvideo\build\intermediates\res\merged\debug\values\values.xml
Error:(186) Attribute "borderWidth" has already been defined
Error:Execution failed for task ':starvideo:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\admins\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by androidjx** [comment]
导完包以后就出现这样的错误了
