### ISSUE TITLE
How to change the frequency of the waves ? 

### ISSUE THREAD

**Issue by zhuxiujia** [tangqi92/WaveLoadingView#23]
How to change the frequency of the waves ?

**Comment by tangqi92** [comment]
You can use attribute 'wlv_waveAmplitude' to change the frequency of the waves or use attribute 'wlv_progressValue' to change the progress value of the waves.

You can also use 'setAmplitudeRatio()' and 'setProgressValue()'

**Comment by zhuxiujia** [comment]
i readed your code without set the wave objectAnimation Time mothed?

**Comment by tangqi92** [comment]
Sorry, I didn't have time to respond to you yesterday because I was too busy.

It does not support it at present.

**Comment by piratch** [comment]
can i custom shape with drawable

**Comment by tangqi92** [comment]
The currently supported shapes circular, triangle and rectangle. You can use 'app:wlv_shapeType' in .xml or 'setShapeType' in .java @piratch

**Comment by tangqi92** [comment]
Hi @zhuxiujia 

I am very very sorry to reply to you so late.

I just updated the library to v0.3.5, now it supports to change the frequency of the waves .

You just need to call the method 'setAnimDuration()'.

I hope you will like it.
Finally, thank you for your support.
