### ISSUE TITLE
setProgressValue() 没有更改 mProgressValue 属性

### ISSUE THREAD

**Issue by zhengfuwang** [tangqi92/WaveLoadingView#3]
this.mProgressValue = progress;

如果不设置的话， getProgressValue() 的值一直是初始的那个 。

**Comment by tangqi92** [comment]
@zhengfuwang 你好，现在这个 bug 已经修好了，最新的代码已经上传，不过 jcenter 那还没过，你要使用的话可以手动导入，最后真心感谢你的反馈：）
