### ISSUE TITLE
not able to set max progress value

### ISSUE THREAD

**Issue by mrgogomaster** [tangqi92/WaveLoadingView#39]
i am not able to set max value of wave  default it is taking 100 please help me to set max value of progress

**Comment by tangqi92** [comment]
Hi mrgogomaster,

You can set max progress value by:`app:wlv_progressValue="100"` or `mWaveLoadingView.setProgressValue(100)`

**Comment by mrgogomaster** [comment]
I can set progress values by setting these progress value i wanted to set max progress value .thanks

**Comment by TejalPatel145** [comment]
I also want to set max progress value to set different progress at different level. Is it Possible?

**Comment by jaydeepbhayani** [comment]
@TejalPatel145 
YES, U CAN PUT if else conditions for your variation. 
if (level <= 50) {
                mWaveLoadingView.setProgressValue(level);
}

**Comment by IvanNoeAlvarez** [comment]
You can use setWaterLevelRatio to modify the water level (0 to 1) while having a different progressValue. Note that must be called after setProgressValue has taken effect, because the animation.
