### ISSUE TITLE
Errors with setWaveColor and setBorderColor

### ISSUE THREAD

**Issue by AreaNovi** [tangqi92/WaveLoadingView#6]
I am able to set the various parameters inside the java code (amplitude, titles, border size, progress value), but when I try to use setWaveColor or setBorderColor, I get for both of them the following error:
java.lang.IllegalArgumentException: width and height must be > 0

Everithing except these errors works fine and I can see correctly the views. So, at the moment, it's not possible for me to change the color of the View depending on some values in the code.

Thanks

**Comment by tangqi92** [comment]
@AreaNovi Hi,
Sorry to keep you waiting, I made a stupid mistake, and now has been fixed. You can try to use the latest version 0.1.5 which i just updated.

Thank you for your support again!
