### ISSUE TITLE
Shape types

### ISSUE THREAD

**Issue by ParhamAhmadi** [tangqi92/WaveLoadingView#7]
Hi again 
It works fine for me without any bug
Thanks for that. 
@tangqi92 Is it possible to add different shapes like rectangle,Triangle,...etc
 it will be more compatible and more attractive

**Comment by ParhamAhmadi** [comment]
I'm waiting @tangqi92

**Comment by ParhamAhmadi** [comment]
What happened @tangqi92? 
I'm still waiting

**Comment by rafaelcorreiapoli** [comment]
I also would like to use Rectangle shape

**Comment by cabrinhaFx** [comment]
same =) Would love to be able to fill my progressbar with your awesome wave anim =)

**Comment by tangqi92** [comment]
Hi guys,

I have updated the library to v0.2.1 and added some shapes like Rectangle, Round Rectangle, Triangle（4 directions）

I hope you will like it !

@ParhamAhmadi @rafaelcorreiapoli @cabrinhaFx
