### ISSUE TITLE
setprogressvalue从0-100波浪由高到低？

### ISSUE THREAD

**Issue by Jacky-Xu** [tangqi92/WaveLoadingView#8]
能不能由低到高的绘制波浪？

**Comment by tangqi92** [comment]
居然之前没有发现，之前的逻辑是反的，这个我会在下个版本进行更新，不过最近都在忙其他的，所以要稍稍晚一点才会接着更新这个库 (>_<｡) （现在不影响你使用的话，请你先容忍下(*^_^*)）

**Comment by ParhamAhmadi** [comment]
@tangqi92 Is it possible to change shape type?
i mean another shapes like triangle , ....

**Comment by Jacky-Xu** [comment]
@tangqi92  好的，大神，祝你新年快乐，尽快更新！嘿嘿

**Comment by tangqi92** [comment]
@Jacky-Xu 我刚刚将库更新至 v0.2.0 了，已经将逻辑改过来了，你稍后可以尝试的下。

**Comment by Jacky-Xu** [comment]
@tangqi92  好的 我更新最新版本试试。

**Comment by Jacky-Xu** [comment]
compile 'me.itangqi.waveloadingview:library:2.0.0' 写错了，应该是 compile 'me.itangqi.waveloadingview:library:0.2.0'，赶紧改一下，2.0.0gradle同步不了。

**Comment by tangqi92** [comment]
@Jacky-Xu 感谢反馈，已经改过来了。
