### ISSUE TITLE
关于4.0模拟器显示问题

### ISSUE THREAD

**Issue by kaku2015** [tangqi92/WaveLoadingView#9]
运行在AS 4.0模拟器上，有个显示问题。
见下图：↓
![4 0](https://cloud.githubusercontent.com/assets/12185465/13729896/b00cab2e-e97a-11e5-866d-93cb54553da0.png)

progressValue 设置的是5，上方区域被填充了（应该为透明）

**Comment by tangqi92** [comment]
@kaku2015 你好，感谢你反馈。

我大概知道了问题出在了哪。（发布时并没有在 4.4.4 以下进行测试）

如果你急需使用，可以将 `amplitude` 值设置成 100，能暂时解决你所说的问题。

我会在下个版本中修复你的 BUG.

谢。

**Comment by kaku2015** [comment]
了解，谢谢！
